###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "feigei",
    "password": "MySuperSecretPassword123!"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "linda",
    "password": "LindasSuperSecretPasswordWOW321!"
}