GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/203412312321

###
DELETE http://localhost:3001/api/persons/1

###
DELETE http://localhost:3001/api/persons/203412312321

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Yufei Cui",
    "number": "647-000-0000"
}

###
PUT http://localhost:3001/api/persons/6108d312269ffd7961f1337a
Content-Type: application/json

{
    "name": "Yufei Cui",
    "number": "416-111-1111"
}