###
GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{

} 

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "Do you smell what The Rock is cooking?",
  "author": "Yufei Cui"
}

###
DELETE http://localhost:3003/api/blogs/615694335e491436e09bebff


###
PUT http://localhost:3003/api/blogs/610debdfe4f438a2e460461d
Content-Type: application/json

{
  "title": "Do you smell what The Rock is cooking?",
  "author": "Yufei Cui",
  "likes": 0
}