GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Testing create notes POST request using VS REST extension",
    "important": true
}